// app/components/NewLeadForm.vue
<script setup lang="ts">
import { api } from "@@/convex/_generated/api"
import type { Id } from "@@/convex/_generated/dataModel"

const emit = defineEmits(["success", "close"])

const state = reactive({
  title: "",
  description: "",
  category: "",
  owner: "",
  issueYear: undefined as number | undefined,
  issueNumber: undefined as number | undefined
})

interface SelectedFile {
  file: File
  storageId?: string
  status: "pending" | "uploading" | "done" | "error"
}

const selectedFiles = ref<SelectedFile[]>([])

const fixedCategories = ["Grüezi", "Rückblick", "Serie"]
const items = ref<string[]>([])

const categoryItems = computed(() => {
  return [...fixedCategories, ...items.value]
})

const onCreateCategory = (item: string) => {
  items.value.push(item)
  state.category = item
}

const { mutate: createLead } = useConvexMutation(api.leads.createLead)
const { mutate: generateUploadUrl } = useConvexMutation(api.files.generateUploadUrl)

const onFileChange = (event: Event) => {
  const target = event.target as HTMLInputElement
  if (!target.files) return

  const files = Array.from(target.files)
  files.forEach((file) => {
    selectedFiles.value.push({
      file,
      status: "pending"
    })
  })

  // Reset input
  target.value = ""
}

const removeFile = (index: number) => {
  selectedFiles.value.splice(index, 1)
}

const uploadFiles = async () => {
  const uploads = selectedFiles.value.map(async (item) => {
    if (item.status === "done") return

    item.status = "uploading"
    try {
      const postUrl = await generateUploadUrl({})
      const result = await fetch(postUrl, {
        method: "POST",
        headers: { "Content-Type": item.file.type },
        body: item.file
      })
      const { storageId } = await result.json()
      item.storageId = storageId
      item.status = "done"
    } catch (error) {
      console.error("File upload failed:", error)
      item.status = "error"
    }
  })

  await Promise.all(uploads)
}

const onSubmit = async () => {
  if (!state.title) return

  try {
    await uploadFiles()

    const attachments = selectedFiles.value
      .filter(f => f.status === "done" && f.storageId)
      .map(f => ({
        storageId: f.storageId as Id<"_storage">,
        name: f.file.name,
        contentType: f.file.type,
        size: f.file.size
      }))

    await createLead({
      title: state.title,
      description: state.description || undefined,
      category: state.category || undefined,
      owner: state.owner || undefined,
      issue: (state.issueYear && state.issueNumber)
        ? {
            year: Number(state.issueYear),
            number: Number(state.issueNumber)
          }
        : undefined,
      attachments
    })

    emit("success")
  } catch (error) {
    console.error("Failed to create lead:", error)
  }
}
</script>

<template>
  <UForm
    :state="state"
    class="space-y-4"
    @submit="onSubmit"
  >
    <UFormField
      label="Title"
      name="title"
      required
      class="w-full"
    >
      <UInput
        v-model="state.title"
        placeholder="Lead title"
        class="w-full font-bold text-lg"
        size="lg"
        autofocus
      />
    </UFormField>

    <UFormField
      label="Description"
      name="description"
      class="w-full"
    >
      <UTextarea
        v-model="state.description"
        placeholder="Lead description"
        class="w-full"
        :rows="4"
        size="md"
      />
    </UFormField>

    <div class="flex flex-col gap-4">
      <h3 class="text-sm font-medium text-slate-700 dark:text-slate-300">
        Attachments
      </h3>

      <div
        v-if="selectedFiles.length > 0"
        class="space-y-2 mb-2"
      >
        <div
          v-for="(item, index) in selectedFiles"
          :key="index"
          class="flex items-center justify-between p-3 rounded-lg bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800 group"
        >
          <div class="flex items-center gap-3 overflow-hidden">
            <div class="w-10 h-10 rounded bg-white dark:bg-slate-900 flex items-center justify-center border border-slate-100 dark:border-slate-800 flex-shrink-0">
              <UIcon
                v-if="item.status === 'uploading'"
                name="i-lucide-loader-2"
                class="w-5 h-5 animate-spin text-primary"
              />
              <UIcon
                v-else-if="item.status === 'done'"
                name="i-lucide-check-circle-2"
                class="w-5 h-5 text-green-500"
              />
              <UIcon
                v-else-if="item.status === 'error'"
                name="i-lucide-alert-circle"
                class="w-5 h-5 text-red-500"
              />
              <UIcon
                v-else
                name="i-lucide-file"
                class="w-5 h-5 text-slate-400"
              />
            </div>
            <div class="flex flex-col overflow-hidden">
              <span class="text-sm font-medium text-slate-900 dark:text-white truncate">
                {{ item.file.name }}
              </span>
              <span class="text-xs text-slate-500">
                {{ (item.file.size / 1024 / 1024).toFixed(2) }} MB
              </span>
            </div>
          </div>
          <UButton
            icon="i-lucide-x"
            color="neutral"
            variant="ghost"
            size="xs"
            class="opacity-0 group-hover:opacity-100 transition-opacity"
            @click="removeFile(index)"
          />
        </div>
      </div>

      <div class="relative">
        <input
          id="file-upload"
          type="file"
          multiple
          class="hidden"
          @change="onFileChange"
        >
        <label
          for="file-upload"
          class="flex flex-col items-center justify-center w-full h-24 border-2 border-dashed border-slate-200 dark:border-slate-800 rounded-xl hover:border-primary/50 hover:bg-primary/5 dark:hover:bg-primary/10 transition-all cursor-pointer group"
        >
          <div class="flex items-center gap-2 text-slate-500 group-hover:text-primary transition-colors">
            <UIcon
              name="i-lucide-paperclip"
              class="w-5 h-5"
            />
            <span class="text-sm font-medium">Add Attachments</span>
          </div>
          <span class="text-xs text-slate-400 mt-1">Upload relevant documents or images</span>
        </label>
      </div>
    </div>

    <div class="grid grid-cols-2 gap-4 pt-4">
      <UFormField
        label="Category"
        name="category"
      >
        <UInputMenu
          v-model="state.category"
          :items="categoryItems"
          placeholder="Select category"
          open-on-focus
          class="w-full"
          create-item
          size="md"
          @create="onCreateCategory"
        />
      </UFormField>

      <UFormField
        label="Owner"
        name="owner"
      >
        <UInput
          v-model="state.owner"
          placeholder="Lead owner"
          class="w-full"
          size="md"
        />
      </UFormField>
    </div>

    <div class="pt-4 border-t border-slate-100 dark:border-slate-800">
      <h3 class="text-sm font-medium text-slate-700 dark:text-slate-300 mb-4">
        Issue
      </h3>
      <div class="flex items-center gap-4">
        <UFormField
          label="Number"
          name="issueNumber"
          class="flex-1"
        >
          <UInput
            v-model="state.issueNumber"
            type="number"
            placeholder="No."
            size="md"
          />
        </UFormField>
        <div class="pt-6 text-xl text-slate-400 font-light">
          /
        </div>
        <UFormField
          label="Year"
          name="issueYear"
          class="flex-1"
        >
          <UInput
            v-model="state.issueYear"
            type="number"
            placeholder="YY"
            size="md"
          />
        </UFormField>
      </div>
    </div>

    <div class="flex justify-end gap-3 pt-6">
      <UButton
        type="button"
        label="Cancel"
        color="neutral"
        variant="ghost"
        @click="emit('close')"
      />
      <UButton
        type="submit"
        label="Create Lead"
        color="primary"
        size="lg"
        class="px-8 shadow-lg shadow-primary/20"
      />
    </div>
  </UForm>
</template>

// app/NewLeadForm.tsx
"use client";

import { ChangeEvent, DragEvent, FormEvent, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { IssueField, type IssueFieldParts } from "@/components/issueField";
import { cn } from "@/lib/utils";
import { File as FileIcon, Upload, X } from "lucide-react";

const fieldClassName =
  "h-8 w-full border border-zinc-300 bg-white px-2 text-sm text-zinc-900 outline-none focus:border-zinc-500 dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-100 dark:focus:border-zinc-500";
const labelClassName = "text-sm font-medium text-zinc-900 dark:text-zinc-100";

type Attachment = {
  storageId: Id<"_storage">;
  name: string;
  contentType: string;
  size: number;
  previewUrl?: string;
};

export function NewLeadForm({
  onCancel,
  onCreated,
}: {
  onCancel: () => void;
  onCreated: () => void;
}) {
  const createLead = useMutation(api.leads.create);
  const generateUploadUrl = useMutation(api.leads.generateUploadUrl);

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [tag, setTag] = useState("");
  const [source, setSource] = useState("");
  const [issue, setIssue] = useState<IssueFieldParts>({ number: "", year: "" });
  const [attachments, setAttachments] = useState<Attachment[]>([]);
  const [isDraggingOver, setIsDraggingOver] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const uploadFiles = async (files: FileList | File[]) => {
    const fileList = Array.from(files);
    if (fileList.length === 0) return;
    setError(null);
    setIsUploading(true);
    try {
      const uploaded = await Promise.all(
        fileList.map(async (file) => {
          const uploadUrl = await generateUploadUrl();
          const result = await fetch(uploadUrl, {
            method: "POST",
            headers: { "Content-Type": file.type },
            body: file,
          });
          if (!result.ok) throw new Error(`Failed to upload ${file.name}`);
          const { storageId } = (await result.json()) as { storageId: Id<"_storage"> };
          return {
            storageId,
            name: file.name,
            contentType: file.type,
            size: file.size,
            previewUrl: file.type.startsWith("image/") ? URL.createObjectURL(file) : undefined,
          };
        }),
      );
      setAttachments((prev) => [...prev, ...uploaded]);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to upload file");
    } finally {
      setIsUploading(false);
    }
  };

  const onFileInputChange = (event: ChangeEvent<HTMLInputElement>) => {
    if (event.target.files) void uploadFiles(event.target.files);
    event.target.value = "";
  };

  const onDrop = (event: DragEvent<HTMLLabelElement>) => {
    event.preventDefault();
    setIsDraggingOver(false);
    if (event.dataTransfer.files) void uploadFiles(event.dataTransfer.files);
  };

  const removeAttachment = (storageId: Id<"_storage">) => {
    setAttachments((prev) => {
      const target = prev.find((attachment) => attachment.storageId === storageId);
      if (target?.previewUrl) URL.revokeObjectURL(target.previewUrl);
      return prev.filter((attachment) => attachment.storageId !== storageId);
    });
  };

  const onSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError(null);
    setIsSubmitting(true);
    try {
      const plannedIssue =
        issue.number && issue.year
          ? { number: Number(issue.number), year: Number(issue.year) }
          : undefined;
      await createLead({
        title,
        description: description || undefined,
        tag: tag || undefined,
        source: source || undefined,
        plannedIssue,
        attachments: attachments.map(({ storageId, name, contentType, size }) => ({
          storageId,
          name,
          contentType,
          size,
        })),
      });
      onCreated();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create lead");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={onSubmit} className="mt-4 space-y-4">
      <div className="space-y-1">
        <label htmlFor="lead-title" className={labelClassName}>
          Title
        </label>
        <input
          id="lead-title"
          required
          value={title}
          onChange={(event) => setTitle(event.target.value)}
          className={fieldClassName}
        />
      </div>

      <div className="space-y-1">
        <label htmlFor="lead-description" className={labelClassName}>
          Description
        </label>
        <textarea
          id="lead-description"
          rows={3}
          value={description}
          onChange={(event) => setDescription(event.target.value)}
          className={cn(fieldClassName, "h-auto resize-none py-1.5")}
        />
      </div>

      <div className="space-y-1">
        <label htmlFor="lead-category" className={labelClassName}>
          Tag
        </label>
        <input
          id="lead-category"
          value={tag}
          onChange={(event) => setTag(event.target.value)}
          className={fieldClassName}
        />
      </div>

      <div className="space-y-1">
        <label htmlFor="lead-owner" className={labelClassName}>
          Source
        </label>
        <input
            id="lead-source"
            value={source}
            onChange={(event) => setSource(event.target.value)}
            className={fieldClassName}
        />
      </div>

      <div className="space-y-1">
        <label htmlFor="lead-issue" className={labelClassName}>
          Issue
        </label>
        <IssueField id="lead-issue" onValueChange={(_, parts) => setIssue(parts)} />
      </div>

      <div className="space-y-2">
        <span className={labelClassName}>Attachments</span>
        <label
          htmlFor="lead-attachments"
          onDragOver={(event) => {
            event.preventDefault();
            setIsDraggingOver(true);
          }}
          onDragLeave={() => setIsDraggingOver(false)}
          onDrop={onDrop}
          className={cn(
            "flex flex-col items-center justify-center gap-1 border border-dashed border-zinc-300 px-4 py-6 text-center text-sm text-zinc-500 cursor-pointer dark:border-zinc-700 dark:text-zinc-400",
            isDraggingOver && "border-zinc-500 bg-zinc-50 dark:bg-zinc-900",
          )}
        >
          <Upload className="size-5" />
          <span>
            {isUploading ? "Uploading..." : "Drag and drop files here, or click to browse"}
          </span>
          <input
            id="lead-attachments"
            type="file"
            multiple
            className="hidden"
            onChange={onFileInputChange}
            disabled={isUploading}
          />
        </label>

        {attachments.length > 0 ? (
          <ul className="space-y-1">
            {attachments.map((attachment) => (
              <li
                key={attachment.storageId}
                className="flex items-center gap-2 border border-zinc-200 px-2 py-1.5 text-sm dark:border-zinc-800"
              >
                {attachment.previewUrl ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={attachment.previewUrl}
                    alt={attachment.name}
                    className="size-8 shrink-0 rounded object-cover"
                  />
                ) : (
                  <FileIcon className="size-8 shrink-0 rounded p-1.5 text-zinc-500 dark:text-zinc-400" />
                )}
                <span className="min-w-0 flex-1 truncate text-zinc-900 dark:text-zinc-100">
                  {attachment.name}
                </span>
                <button
                  type="button"
                  onClick={() => removeAttachment(attachment.storageId)}
                  className="shrink-0 text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200"
                  aria-label={`Remove ${attachment.name}`}
                >
                  <X className="size-4" />
                </button>
              </li>
            ))}
          </ul>
        ) : null}
      </div>

      {error ? <p className="text-sm text-red-600">{error}</p> : null}

      <div className="flex justify-end gap-2">
        <Button type="button" variant="outline" onClick={onCancel} disabled={isSubmitting}>
          Cancel
        </Button>
        <Button type="submit" disabled={isSubmitting || isUploading}>
          {isSubmitting ? "Creating..." : "Create Lead"}
        </Button>
      </div>
    </form>
  );
}
