// app/pages/leads/index.vue
<script setup lang="ts">
import { api } from '@@/convex/_generated/api'
import type { Doc } from '@@/convex/_generated/dataModel'

interface Section {
  id: string
  title: string
  leads: Doc<'leads'>[]
}

const { data: leads, isPending } = useConvexQuery(api.leads.list, {})

const groupedSections = computed<Section[]>(() => {
  const leadsData = leads.value
  if (!leadsData) return []

  const sections: Section[] = []

  // 1. New leads (no issue)
  const newLeads = leadsData.filter((l: Doc<'leads'>) => !l.issue)
  if (newLeads.length > 0) {
    sections.push({
      id: 'new',
      title: 'New',
      leads: newLeads
    })
  }

  // 2. Assigned leads grouped by issue
  const assignedLeads = leadsData.filter((l: Doc<'leads'>) => !!l.issue)

  // Sort assigned leads by year then number
  const sortedAssigned = [...assignedLeads].sort((a: Doc<'leads'>, b: Doc<'leads'>) => {
    if (a.issue!.year !== b.issue!.year) return a.issue!.year - b.issue!.year
    return a.issue!.number - b.issue!.number
  })

  // Create unique issue groups
  const issueMap = new Map<string, Section>()

  sortedAssigned.forEach((l: Doc<'leads'>) => {
    const key = `${l.issue!.year}-${l.issue!.number}`
    if (!issueMap.has(key)) {
      const section: Section = {
        id: key,
        title: `${l.issue!.number}/${l.issue!.year}`,
        leads: []
      }
      issueMap.set(key, section)
      sections.push(section)
    }
    issueMap.get(key)!.leads.push(l)
  })

  return sections
})
</script>

<template>
  <UContainer class="py-8">
    <div class="flex justify-between items-end mb-8 pl-1">
      <div>
        <h1 class="text-3xl font-bold tracking-tight text-slate-900 dark:text-white">
          Leads
        </h1>
        <p class="text-slate-500 dark:text-slate-400 mt-1">
          Browse and manage your leads by issue.
        </p>
      </div>
      <UButton
        to="/leads/new"
        icon="i-lucide-plus"
        label="New Lead"
        color="primary"
      />
    </div>

    <div
      v-if="isPending"
      class="flex justify-center py-20"
    >
      <UIcon
        name="i-lucide-loader-2"
        class="w-10 h-10 animate-spin text-primary-500"
      />
    </div>

    <div
      v-else-if="groupedSections.length === 0"
      class="text-center py-20 border-2 border-dashed border-slate-200 dark:border-slate-800 rounded-3xl"
    >
      <div class="bg-slate-50 dark:bg-slate-900/50 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4">
        <UIcon
          name="i-lucide-inbox"
          class="w-10 h-10 text-slate-300"
        />
      </div>
      <h2 class="text-xl font-semibold text-slate-900 dark:text-white mb-2">
        No leads found
      </h2>
      <p class="text-slate-500 mb-6">
        Start by creating your first lead for a specific issue or a general one.
      </p>
      <UButton
        to="/leads/new"
        icon="i-lucide-plus"
        size="lg"
      >
        Create Lead
      </UButton>
    </div>

    <div
      v-else
      class="flex flex-col gap-12"
    >
      <section
        v-for="section in groupedSections"
        :key="section.id"
        class="animate-in fade-in slide-in-from-bottom-2 duration-500"
      >
        <div class="flex items-center gap-4 mb-6 sticky top-0 z-10 py-1 bg-white/80 dark:bg-slate-950/80 backdrop-blur-md">
          <div class="flex items-center gap-3">
            <div
              class="w-8 h-8 rounded-lg flex items-center justify-center text-white font-bold text-xs"
              :class="section.id === 'new' ? 'bg-primary-500' : 'bg-slate-700 dark:bg-slate-600'"
            >
              {{ section.id === 'new' ? 'N' : '#' }}
            </div>
            <h2 class="text-lg font-bold tracking-tight text-slate-900 dark:text-white uppercase">
              {{ section.title }}
            </h2>
          </div>
          <div class="h-px flex-1 bg-slate-200 dark:bg-slate-800" />
          <span class="text-sm font-semibold text-slate-400 dark:text-slate-500 tabular-nums">
            {{ section.leads.length }} {{ section.leads.length === 1 ? 'lead' : 'leads' }}
          </span>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
          <LeadCard
            v-for="lead in section.leads"
            :key="lead._id"
            :lead="lead"
          />
        </div>
      </section>
    </div>
  </UContainer>
</template>

// app/(app)/leads/page.tsx
"use client";

import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import type { FunctionReturnType } from "convex/server";
import { HelpCircle, Mail, User } from "lucide-react";

type Lead = FunctionReturnType<typeof api.leads.list>[number];

function issueLabel(plannedIssue: Lead["plannedIssue"]): string {
  if (!plannedIssue) return "New Leads";
  return `${plannedIssue.number}/${String(plannedIssue.year).slice(-2)}`;
}

function groupByIssue(leads: Lead[]) {
  const groups: { key: string; label: string; leads: Lead[] }[] = [];
  for (const lead of leads) {
    const key = lead.plannedIssue
      ? `${lead.plannedIssue.year}-${lead.plannedIssue.number}`
      : "unassigned";
    const last = groups[groups.length - 1];
    if (last?.key === key) {
      last.leads.push(lead);
    } else {
      groups.push({ key, label: issueLabel(lead.plannedIssue), leads: [lead] });
    }
  }
  return groups;
}

function SourceIcon({ kind }: { kind: NonNullable<Lead["source"]>["kind"] }) {
  if (kind === "Email") return <Mail className="size-4" />;
  if (kind === "User") return <User className="size-4" />;
  return <HelpCircle className="size-4" />;
}

function sourceLabel(source: Lead["source"]): string | null {
  if (!source) return null;
  if (source.kind === "Email") return source.email;
  if (source.kind === "Other") return source.name;
  return source.label;
}

function LeadCard({ lead }: { lead: Lead }) {
  const source = lead.source;
  const label = sourceLabel(source);

  return (
    <div className="relative border border-zinc-200 bg-white p-3 dark:border-zinc-800 dark:bg-zinc-950">
      {lead.tag ? (
        <span className="absolute top-2 right-2 border border-zinc-200 px-1.5 py-0.5 text-[10px] font-medium text-zinc-500 dark:border-zinc-800 dark:text-zinc-400">
          {lead.tag}
        </span>
      ) : null}

      <div className="pr-16">
        <h3 className="font-bold text-zinc-900 dark:text-zinc-100">{lead.title}</h3>
        {lead.description ? (
          <p className="mt-1 line-clamp-3 text-sm text-zinc-600 dark:text-zinc-400">
            {lead.description}
          </p>
        ) : null}
      </div>

      {source && label ? (
        <div className="mt-3 flex items-center gap-1.5 border-t border-zinc-200 pt-2 text-sm text-zinc-600 dark:border-zinc-800 dark:text-zinc-400">
          <SourceIcon kind={source.kind} />
          <span className="truncate">{label}</span>
        </div>
      ) : null}
    </div>
  );
}

export default function LeadsPage() {
  const leads = useQuery(api.leads.list);

  return (
    <section className="w-full">
      <h1 className="text-2xl font-semibold text-zinc-900 dark:text-zinc-100">Leads</h1>

      {leads === undefined ? (
        <p className="mt-4 text-sm text-zinc-600 dark:text-zinc-400">Loading…</p>
      ) : leads.length === 0 ? (
        <p className="mt-4 text-sm text-zinc-600 dark:text-zinc-400">No leads yet.</p>
      ) : (
        <div className="mt-4 space-y-8">
          {groupByIssue(leads).map((group) => (
            <section key={group.key}>
              <h2 className="border-b border-zinc-200 pb-2 text-sm font-semibold text-zinc-500 dark:border-zinc-800 dark:text-zinc-400">
                {group.label}
              </h2>
              <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {group.leads.map((lead) => (
                  <LeadCard key={lead._id} lead={lead} />
                ))}
              </div>
            </section>
          ))}
        </div>
      )}
    </section>
  );
}
